srcds_base_port: 27015
srcds_reserve_ports: 10

# FastDL Base URL
fastdl_url: "https://jackavery.ca/fastdl/tf/"
global_tags:
  - raspy

# Link to SourceBans website
sourcebans:
  website: "https://jackavery.ca/bans/"

# Whether to enable STV by default
stv_enabled: false

# Common "rulesets"
rulesets:
  standard:
    - tf_weapon_criticals 0
    - tf_use_fixed_weaponspreads 1
    - tf_spawn_glows_duration 0
    - tf_spec_xray 0
    - tf_preround_push_from_damage_enable 1
    - tf_avoidteammates_pushaway 0
  rinstagib:
    - tf_weapon_criticals 0
    - tf_use_fixed_weaponspreads 1
    - tf_spawn_glows_duration 0
    - tf_spec_xray 0
    - tf_preround_push_from_damage_enable 1
    - tf_avoidteammates_pushaway 0
    - sv_airaccelerate 150
    - sv_gravity 700
    - sv_alltalk 1
    - mp_friendlyfire 1
    - tf_forced_holiday 2
    - tf_arena_use_queue 0
    - tf_arena_first_blood 0
    - mp_tournament 1
    - mp_chattime 0
  casual:
    - tf_weapon_criticals 1
    - tf_use_fixed_weaponspreads 0
    - tf_spawn_glows_duration 10
    - tf_spec_xray 1
    - tf_preround_push_from_damage_enable 0
    - tf_avoidteammates_pushaway 1

# List of maps
mapcycles:
  rinstagib:
    - cp_process_final
    - cp_sunshine
    - pl_upward
    - plr_hightower
    - cp_orange_gamerland_classic
    - koth_lakeside_final

  all:
    # ad
    - cp_altitude
    - cp_dustbowl
    - cp_egypt_final
    - cp_gorge
    - cp_gravelpit
    - cp_junction_final
    - cp_mercenarypark
    - cp_mossrock
    - cp_mountainlab
    - cp_steel
    # 5cp
    - cp_5gorge
    - cp_badlands
    - cp_coldfront
    - cp_fastlane
    - cp_foundry
    - cp_freight_final1
    - cp_granary
    - cp_gullywash_final1
    - cp_metalworks
    - cp_process_final
    - cp_snakewater_final1
    - cp_standin_final
    - cp_sunshine
    - cp_vanguard
    - cp_well
    - cp_yukon_final
    # 3cp
    - cp_powerhouse
    # koth
    - koth_badlands
    - koth_highpass
    - koth_king
    - koth_lakeside_final
    - koth_harvest_final
    - koth_suijin
    - koth_viaduct
    - koth_cascade
    - koth_brazil
    - koth_lazarus
    - koth_sawmill
    - koth_nucleus
    - koth_harvest_final
    # payload
    - pl_badwater
    - pl_barnblitz
    - pl_borneo
    - pl_enclosure_final
    - pl_frontier_final
    - pl_goldrush
    - pl_hoodoo_final
    - pl_pier
    - pl_rumford_event
    - pl_snowycoast
    - pl_swiftwater_final1
    - pl_thundermountain
    - pl_upward
    # payload (evil version)
    - plr_bananabay
    - plr_hightower
    - plr_nightfall_final
    - plr_pipeline
    # ctf
    - ctf_2fort
    - ctf_doublecross
    - ctf_landfall
    - ctf_sawmill
    - ctf_turbine
    - ctf_well
    # pass time
    - pass_brickyard
    - pass_timbertown
    - pass_district

# Plugins to include on every server
base_plugins:
  - admin-flatfile
  - adminhelp
  - adminmenu
  - antiflood
  - basebans
  - basechat
  - basecomm
  - basecommands
  - basetriggers
  - basevotes
  - clientprefs
  - discord
  - fixstvslot
  - funcommands
  - funvotes
  - mapconfigs
  - nextmap
  - playercommands
  - raspyverse_commands
  - reservedslots
  - sbpp_admcfg
  - sbpp_checker
  - sbpp_comms
  - sbpp_main
  - sbpp_sleuth
  - sm_nocontracker
  - sounds
  - spraytrace
  - stac
  - swag
  - tf2centerprojectiles
  - waitingdoors
  - mapchooser
  - rockthevote
  - nominations

  - nativevotes
  - nativevotes-basevotes
  - nativevotes-basecommands
  - nativevotes_kickvote_immunity
  - nativevotes_mapchooser
  - nativevotes_nominations
  - nativevotes_rockthevote
  - votedelay_changelevel
  - votefailed

###
# Plugin default configurations
###

classrestrict:
  sm_crh_blu_demomen: "-1"
  sm_crh_blu_engineers: "-1"
  sm_crh_blu_heavies: "-1"
  sm_crh_blu_medics: "-1"
  sm_crh_blu_pyros: "-1"
  sm_crh_blu_scouts: "-1"
  sm_crh_blu_snipers: "-1"
  sm_crh_blu_soldiers: "-1"
  sm_crh_blu_spies: "-1"
  sm_crh_classmenu: "1"
  sm_crh_enabled: "0"
  sm_crh_flags: "b"
  sm_crh_immunity: "0"
  sm_crh_red_demomen: "-1"
  sm_crh_red_engineers: "-1"
  sm_crh_red_heavies: "-1"
  sm_crh_red_medics: "-1"
  sm_crh_red_pyros: "-1"
  sm_crh_red_scouts: "-1"
  sm_crh_red_snipers: "-1"
  sm_crh_red_soldiers: "-1"
  sm_crh_red_spies: "-1"
  sm_crh_sounds: "1"

mapchooser:
  # Specifies how many more frags are allowed when map is extended.
  # -
  # Default: "10"
  # Minimum: "5.000000"
  sm_extendmap_fragstep: "10"

  # Specifies how many more rounds each extension makes
  # -
  # Default: "5"
  # Minimum: "1.000000"
  sm_extendmap_roundstep: "5"

  # Specifies how much many more minutes each extension makes
  # -
  # Default: "15"
  # Minimum: "5.000000"
  sm_extendmap_timestep: "15"

  # Specifies if a 'Don't Change' option should be added to early votes
  # -
  # Default: "1"
  # Minimum: "0.000000"
  sm_mapvote_dontchange: "0"

  # Specifies if MapChooser should run an end of map vote
  # -
  # Default: "1"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  sm_mapvote_endvote: "1"

  # Specifies how many past maps to exclude from the vote.
  # -
  # Default: "5"
  # Minimum: "0.000000"
  sm_mapvote_exclude: "0"

  # Number of extensions allowed each map.
  # -
  # Default: "0"
  # Minimum: "0.000000"
  sm_mapvote_extend: "1"

  # Specifies how many maps to include in the vote.
  # -
  # Default: "5"
  # Minimum: "2.000000"
  # Maximum: "6.000000"
  sm_mapvote_include: "5"

  # Specifies whether or not MapChooser should pick a map if no votes are received.
  # -
  # Default: "1"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  sm_mapvote_novote: "1"

  # Specifies if previous maps should be stored persistently.
  # -
  # Default: "0"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  sm_mapvote_persistentmaps: "0"

  # Hold runoff votes if winning choice is less than a certain margin
  # -
  # Default: "0"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  sm_mapvote_runoff: "0"

  # If winning choice has less than this percent of votes, hold a runoff
  # -
  # Default: "50"
  # Minimum: "0.000000"
  # Maximum: "100.000000"
  sm_mapvote_runoffpercent: "50"

  # Specifies when to start the vote based on time remaining.
  # -
  # Default: "3.0"
  # Minimum: "1.000000"
  sm_mapvote_start: "5.0"

  # Specifies when to start the vote base on frags remaining.
  # -
  # Default: "5.0"
  # Minimum: "1.000000"
  sm_mapvote_startfrags: "5.0"

  # Specifies when to start the vote based on rounds remaining. Use 0 on TF2 to start vote during bonus round time
  # -
  # Default: "2.0"
  # Minimum: "0.000000"
  sm_mapvote_startround: "0.0"

  # Specifies how long the mapvote should be available for.
  # -
  # Default: "20"
  # Minimum: "5.000000"
  sm_mapvote_voteduration: "15"

nativevotes:
  # Show current vote progress as chat messages
  # -
  # Default: "0"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  nativevotes_progress_chat: "0"

  # Show current vote progress as console messages to clients
  # -
  # Default: "0"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  nativevotes_progress_client_console: "0"

  # Show current vote progress as console messages
  # -
  # Default: "0"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  nativevotes_progress_console: "1"

  # Show current vote progress in a hint box
  # -
  # Default: "0"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  nativevotes_progress_hintbox: "1"

  # Sets the recommended time in between public votes
  # -
  # Default: "30"
  # Minimum: "0.000000"
  nativevotes_vote_delay: "30"

sourcemod:
  # Specifies how admin activity should be relayed to users.  Add up the values
  # below to get the functionality you want.
  # 1: Show admin activity to non-admins anonymously.
  # 2: If 1 is specified, admin names will be shown.
  # 4: Show admin activity to admins anonymously.
  # 8: If 4 is specified, admin names will be shown.
  # 16: Always show admin names to root users.
  # --
  # Default: 13 (1+4+8)
  sm_show_activity: "15"

  # Specifies whether menu sounds are enabled for menus created by SourceMod.
  # Menu sounds can be further configured in addons/sourcemod/configs/core.cfg.
  # --
  # Default: 1
  sm_menu_sounds: "1"

  # Specifies how long of a delay, in seconds, should be used in between votes 
  # that are: "public" or can be spammed.  Whether or not this delay is obeyed 
  # is dependent on the menu/command.
  # --
  # Default: 30
  sm_vote_delay: "30"

  # Default datetime formatting rules when displaying to clients.
  # For full options, see: http:#www.opengroup.org/onlinepubs/007908799/xsh/strftime.html
  # --
  # Default: %m/%d/%Y - %H:%M:%S
  # 12 hour format: %m/%d/%Y - %I:%M:%S %p
  sm_datetime_format: "%m/%d/%Y - %H:%M:%S"

  # Sets how SourceMod should check immunity levels when administrators target 
  # each other.
  # 0: Ignore immunity levels (except for specific group immunities).
  # 1: Protect from admins of lower access only.
  # 2: Protect from admins of equal to or lower access.
  # 3: Same as 2, except admins with no immunity can affect each other.
  # --
  # Default: 1
  sm_immunity_mode: "1"

  # Sets how many seconds SourceMod should adjust time values for incorrect 
  # server clocks.  This can be positive or negative and will affect every 
  # system time in SourceMod, including logging stamps.
  # --
  # Default: 0
  sm_time_adjustment: "0"

  # Specifies the amount of time that is allowed between chat messages.  This
  # includes the say and say_team commands.  If a client sends a message faster
  # than this time, they receive a flood token.  When the client has accumulated
  # 3 or more tokens, a warning message is shown instead of the chat message.
  # --
  # Requires: antiflood.smx
  # Default: 0.75
  sm_flood_time: "0"

  # Specifies how the reserved slots plugin operates. Valid values are:
  # 0 : Public slots are used in preference to reserved slots. Reserved slots are freed before public slots.
  # 1 : If someone with reserve access joins into a reserved slot, the player with the highest latency and 
  # no reserved slot access (spectator players are selected first) is kicked to make room. Thus, the reserved
  # slots always remains free. The only situation where the reserved slot(s) can become properly occupied is 
  # if the server is full with reserve slot access clients.
  # 2 : The same as sm_reserve_type 1 except once a certain number of admins have been reached, the reserve slot
  # stops kicking people and anyone can join to fill the server. You can use this to simulate having a large
  # number of reserved slots with sm_reserve_type 0 but with only need to have 1 slot unavailable when there are
  # less admins connected.
  # --
  # Requires: reservedslots.smx
  # Default: 0
  sm_reserve_type: "0"

  # Specifies the number of reserved player slots.  Users with the reservation
  # admin flag set will be able to join the server when there are no public slots
  # remaining. If someone does not have this flag, they will be kicked.
  # (Public slots are defined as: maxplayers - number of reserved slots)
  # --
  # Requires: reservedslots.smx
  # Default: 0
  sm_reserved_slots: "0"

  # Specifies whether or not reserved slots will be hidden (subtracted from max
  # slot count). Valid values are 0 (Visible) or 1 (Hidden).
  # --
  # Requires: reservedslots.smx
  # Default: 0
  sm_hide_slots: "0"

  # Specifies whether or not non-admins can send messages to admins using
  # say_team @<message>. Valid values are 0 (Disabled) or 1 (Enabled)
  # --
  # Requires: basechat.smx
  # Default: 1
  sm_chat_mode: "1"

  # Specifies whether or not: "timeleft" will automatically be triggered every
  # x seconds. Valid values are 0 (Disabled) to 1800 seconds.
  # --
  # Requires: basetriggers.smx
  # Default: 0
  sm_timeleft_interval: "0"

  # Specifies whether or not chat triggers are broadcast to the server or just
  # the player who requested the info trigger. Valid values are 0 (Disabled) or
  # 1 (Enabled)
  # --
  # Requires: basetriggers.smx
  # Default: 0
  sm_trigger_show: "0"

  # Specifies whether or not to display vote progress to clients in the
  #: "hint" box (near the bottom of the screen in most games).
  # Valid values are 0 (Disabled) or 1 (Enabled).
  # --
  # Default: 0
  sm_vote_progress_hintbox: "0"

  # Specifies whether or not to display vote progress to clients in the
  # chat area. Valid values are 0 (Disabled) or 1 (Enabled).
  # --
  # Default: 0
  sm_vote_progress_chat: "0"

  # Specifies whether or not to display vote progress in the server console.
  # Valid values are 0 (Disabled) or 1 (Enabled).
  # --
  # Default: 0
  sm_vote_progress_console: "0"

  # Specifies whether or not to display vote progress to clients in the
  # client console. Valid values are 0 (Disabled) or 1 (Enabled).
  # --
  # Default: 0
  sm_vote_progress_client_console: "0"

soap_tf2dm:
  # Set to 1 to draw boxes around spawn points when players spawn. Set to 2 to draw ALL spawn points constantly. For debugging.
  # -
  # Default: "0"
  # Minimum: "0.000000"
  # Maximum: "2.000000"
  soap_debugspawns: "0"

  # Disables the ammo packs on map load.
  # -
  # Default: "0"
  soap_disableammopacks: "0"

  # Disables the resupply cabinets on map load
  # -
  # Default: "1"
  soap_disablecabinet: "1"

  # Disables the health packs on map load.
  # -
  # Default: "0"
  soap_disablehealthpacks: "0"

  # Percentage of HP to restore based on amount of damage given. .5 = 50%. Should not be used with soap_kill_heal_static.
  # -
  # Default: "0.0"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  soap_dmg_heal_ratio: "0.0"

  # Enable falling back to spawns from other versions of the map if no spawns are configured for the current map.
  # -
  # Default: "1"
  soap_fallback_config: "1"

  # Time limit enforcement, used to fix a never-ending round issue on gravelpit.
  # -
  # Default: "1"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  soap_forcetimelimit: "1"

  # Enable ammo restoration on kills.
  # -
  # Default: "1"
  soap_kill_ammo: "1"

  # Percentage of HP to restore on kills. .5 = 50%. Should not be used with soap_kill_heal_static.
  # -
  # Default: "0.5"
  # Minimum: "0.000000"
  # Maximum: "1.000000"
  soap_kill_heal_ratio: "0.5"

  # Amount of HP to restore on kills. Exact value applied the same to all classes. Should not be used with soap_kill_heal_ratio.
  # -
  # Default: "0"
  soap_kill_heal_static: "0"

  # Start the heal-over-time regen immediately after a kill.
  # -
  # Default: "1"
  soap_kill_start_regen: "1"

  # Prevents players from inheriting their velocity from previous lives when spawning thru SOAP.
  # -
  # Default: "1"
  soap_novelocityonspawn: "1"

  # Force all doors to open. Required on maps like cp_well.
  # -
  # Default: "1"
  soap_opendoors: "0"

  # Seconds after damage before regeneration.
  # -
  # Default: "5.0"
  soap_regendelay: "5.0"

  # Health added per regeneration tick. Set to 0 to disable.
  # -
  # Default: "1"
  soap_regenhp: "1"

  # Delay between regeration ticks.
  # -
  # Default: "0.1"
  soap_regentick: "0.1"

  # Print killer's health to victim on death.
  # -
  # Default: "1"
  soap_showhp: "1"

  # Spawn timer.
  # -
  # Default: "1.5"
  soap_spawn_delay: "1.5"

  # Enable random spawns.
  # -
  # Default: "1"
  soap_spawnrandom: "1"

  # Enable random spawns independent of team
  # -
  # Default: "0"
  soap_teamspawnrandom: "1"

advancedinfiniteammo:
  # Advanced Infinite Ammo will work for admins only, 1 = Completely Admin Only, 2 = Admin Only but the commands will work on non-admins
  # -
  # Default: "0"
  sm_aia_adminonly: "0"

  # Advanced Infinite Ammo for everyone
  # -
  # Default: "0"
  sm_aia_all: "0"

  # Infinite Ammo will be globally disabled
  # -
  # Default: "1"
  sm_aia_ammo: "1"

  # Advanced Infinite Ammo will work for bots
  # -
  # Default: "1"
  sm_aia_bots: "1"

  # Show Advanced Infinite Ammo changes in chat
  # -
  # Default: "1"
  sm_aia_chat: "0"

  # Infinite Clip will be globally disabled
  # -
  # Default: "1"
  sm_aia_clip: "1"

  # Infinite Cloak will be globally disabled
  # -
  # Default: "1"
  sm_aia_cloak: "1"

  # Weapons indexes to not give infinite ammo, separated by semicolons
  # -
  # Default: ""
  sm_aia_disabledweapons: ""

  # Infinite Extra Stuff will be globally disabled
  # -
  # Default: "1"
  sm_aia_extrastuff: "0"

  # Log Advanced Infinite Ammo commands
  # -
  # Default: "1"
  sm_aia_log: "1"

  # Infinite Metal will be globally disabled
  # -
  # Default: "1"
  sm_aia_metal: "1"

  # Advanced Infinite Ammo for everyone on round win
  # -
  # Default: "1"
  sm_aia_roundwin: "1"

  # Infinite Sentry Ammo will be globally disabled
  # -
  # Default: "1"
  sm_aia_sentryammo: "1"

  # Infinite Spells will be globally disabled
  # -
  # Default: "1"
  sm_aia_spells: "1"

  # Advanced Infinite Ammo for everyone during waiting for players phase
  # -
  # Default: "1"
  sm_aia_waitingforplayers: "1"

rinstagib:
  ri_enabled: "0"
  ri_leaderboard: "1"
  ri_launcher_damage: "5"
  ri_launcher_consistent: "1.0"
  ri_launcher_projspeed: "1.0"
  ri_launcher_freerj: "1.0"
  ri_launcher_radius: "0.1"
  ri_melee_damage: "4"
  ri_rail_damage: "80"
  ri_rail_gibdamage: "200"
  ri_rail_rateslow: "2"
  ri_rail_snipe_floor: "512"
  ri_rail_snipe_bonus: "25"
  ri_rail_speed_floor: "300"
  ri_rail_speed_horizontal: "1"
  ri_rail_speed_bonus: "20"
