# https://developer.valvesoftware.com/wiki/Sv_region
srcds_region: 0
srcds_base_port: 27015
srcds_reserve_ports: 10
daily_restart_hour_utc: 12
cpuset_offset: 0 # for when you have multiple networks on one machine: 0-indexed

instances:
  - name: "controlpoint"
    hostname: "Control Point Official | 2009 Nostalgia"
    maxplayers: 24
    mapcycle: "controlpoint"
    ruleset: "controlpoint"
    timelimit: 30
    relay_channel: 1270483262288035912

    # most plugin configurations support instance- and ruleset-level (tf2.yml) overrides
    # on top of the MOTD, tags, plugins, and more
