srcds_region: 0

instances:
  - name: "respawnroom"
    hostname: "The Respawn Room"
    maxplayers: 18
    mapcycle: "respawnroom"
    ruleset: "respawnroom"
    timelimit: 30
    stv_name: "/call to report players"
    relay_bot:
      channel: 1177733445854707742
      rcon_users:
        - 97441955893477376
        - 577603696125411364
